logger:
  level: INFO

client:
  requests:
    timeout: 6 # in second
  selenium:
    timeout: 60 # in second

traffic_limit:
  global_throttle:
    size: 20

jobs:
  package: engine.job_portal
  module: Job
  list:
    - USAJob:
        type: one-off
    - GitHubJob:
        type: sec
        sec: 10
        pool_size: 10
#    - ThirdJob:
#        type: cron
#        cron: "19,39,59 * * * *"
#        pool_size: 10
