logger:
  level: INFO

client:
  requests:
    timeout: 6 # in second
  selenium:
    timeout: 60 # in second

traffic_limit:
  global_throttle:
    size: 20

jobs:
  package: engine.job
  module: Job
  list:
    USAJob:
        type: one-off
        user_agent: rj_jnu@outlook.com
        auth_key: 2Gkkyrddz2Skk1czvO03iqRzUmPBqB6WCaTXUV1O/pc=
    GitHubJob:
        type: sec
        sec: 10
        pool_size: 10
#   ThirdJob:
#        type: cron
#        cron: "19,39,59 * * * *"
#        pool_size: 10
