logger:
  level: INFO

app_port: 8000

mongodb:
  ip: 127.0.0.1
  port: 27017
  user_name:
  password:
  db_name: tech_radar

client:
  requests:
    timeout: 6 # in second
  selenium:
    timeout: 60 # in second

traffic_limit:
  global_throttle:
    size: 20

jobs:
  package: engine.job
  module: Job
  list:
    InitializationJob:
        type: sec
        sec: 30
        pool_size: 1
    USAJob:
        type: sec
        sec: 30
        pool_size: 10
        user_agent: rj_jnu@outlook.com
        auth_key: 2Gkkyrddz2Skk1czvO03iqRzUmPBqB6WCaTXUV1O/pc=
    GitHubJob:
        type: sec
        sec: 30
        pool_size: 10
#   ThirdJob:
#        type: one-off
#        type: cron
#        cron: "19,39,59 * * * *"
#        pool_size: 10
